from fastapi import FastAPI, Request, Form, HTTPException

from fastapi.responses import HTMLResponse, RedirectResponse, Response

from fastapi.templating import Jinja2Templates

import psycopg

from psycopg.rows import dict_row


from typing import Dict, List, Tuple, Optional

from itertools import combinations

import os



ADMIN_PASSWORD = os.environ.get("ADMIN_PASSWORD", "")



DATABASE_URL = os.environ.get("DATABASE_URL", "")



app = FastAPI()

templates = Jinja2Templates(directory="templates")





def db():
    if not DATABASE_URL:
        raise RuntimeError("DATABASE_URL is not set")
    return psycopg.connect(DATABASE_URL, row_factory=dict_row)


def require_admin(password: str | None):
    if not ADMIN_PASSWORD:
        return
    if (password or "") != ADMIN_PASSWORD:
        raise HTTPException(status_code=403, detail="Forbidden")


def init_db() -> None:
    conn = db()
    cur = conn.cursor()

    cur.execute("""
        CREATE TABLE IF NOT EXISTS players (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL UNIQUE
        )
    """)

    cur.execute("""
        CREATE TABLE IF NOT EXISTS matches (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            p1_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
            p2_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
            p1_sets INTEGER NOT NULL,
            p2_sets INTEGER NOT NULL,
            p1_points INTEGER NOT NULL DEFAULT 0,
            p2_points INTEGER NOT NULL DEFAULT 0,
            sets_detail TEXT NOT NULL DEFAULT '',
            played_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(p1_id, p2_id)
        )
    """)

    cur.execute("""
        CREATE TABLE IF NOT EXISTS schedule (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            day_no INTEGER NOT NULL,
            order_in_day INTEGER NOT NULL,
            p1_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
            p2_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
            UNIQUE(p1_id, p2_id)
        )
    """)

    conn.commit()
    conn.close()


@app.on_event("startup")

def _startup():

    init_db()





def get_players(conn) -> List[Dict]:

    return conn.execute("SELECT id, name FROM players ORDER BY LOWER(name), name").fetchall()





def get_matches(conn) -> List[Dict]:

    return conn.execute("""

        SELECT m.id, m.p1_id, p1.name AS p1_name, m.p2_id, p2.name AS p2_name,

               m.p1_sets, m.p2_sets, m.p1_points, m.p2_points, m.sets_detail, m.played_at

        FROM matches m

        JOIN players p1 ON p1.id = m.p1_id

        JOIN players p2 ON p2.id = m.p2_id

        ORDER BY m.played_at DESC

    """).fetchall()





def get_schedule(conn):

    return conn.execute("""

        SELECT s.id, s.day_no, s.order_in_day,

               s.p1_id, p1.name AS p1_name,

               s.p2_id, p2.name AS p2_name

        FROM schedule s

        JOIN players p1 ON p1.id = s.p1_id

        JOIN players p2 ON p2.id = s.p2_id

        ORDER BY s.day_no ASC, s.order_in_day ASC

    """).fetchall()





def normalize_pair(p1_id: int, p2_id: int, payload: Dict) -> Tuple[int, int, Dict]:

    if p1_id < p2_id:

        return p1_id, p2_id, payload



    swapped = dict(payload)

    swapped["p1_sets"], swapped["p2_sets"] = payload["p2_sets"], payload["p1_sets"]

    swapped["p1_points"], swapped["p2_points"] = payload["p2_points"], payload["p1_points"]



    detail = payload.get("sets_detail", "")

    if detail:

        parts = [p.strip() for p in detail.split(",") if p.strip()]

        swapped_parts = []

        for part in parts:

            if "-" in part:

                a, b = part.split("-", 1)

                swapped_parts.append(f"{b.strip()}-{a.strip()}")

            else:

                swapped_parts.append(part)

        swapped["sets_detail"] = ",".join(swapped_parts)



    return p2_id, p1_id, swapped





def parse_sets_best_of_3(

    s1a: Optional[int], s1b: Optional[int],

    s2a: Optional[int], s2b: Optional[int],

    s3a: Optional[int], s3b: Optional[int],

) -> Optional[Dict]:

    raw = [(s1a, s1b), (s2a, s2b), (s3a, s3b)]



    sets = []

    for a, b in raw:

        if a is None and b is None:

            continue

        if a is None or b is None:

            return None

        if a < 0 or b < 0:

            return None

        if a == b:

            return None

        sets.append((a, b))



    if len(sets) < 2 or len(sets) > 3:

        return None



    p1_sets = 0

    p2_sets = 0

    p1_points = 0

    p2_points = 0

    detail_parts = []



    for a, b in sets:

        p1_points += a

        p2_points += b

        detail_parts.append(f"{a}-{b}")



        if a > b:

            p1_sets += 1

        else:

            p2_sets += 1



    if not (p1_sets == 2 or p2_sets == 2):

        return None



    if (p1_sets == 2 and p2_sets == 0) or (p2_sets == 2 and p1_sets == 0):

        if len(sets) != 2:

            return None



    if (p1_sets == 2 and p2_sets == 1) or (p2_sets == 2 and p1_sets == 1):

        if len(sets) != 3:

            return None



    return {

        "p1_sets": p1_sets,

        "p2_sets": p2_sets,

        "p1_points": p1_points,

        "p2_points": p2_points,

        "sets_detail": ",".join(detail_parts),

    }





def compute_table(players: List[Dict], matches: List[Dict]) -> List[Dict]:

    stats: Dict[int, Dict] = {}

    for p in players:

        stats[p["id"]] = {

            "id": p["id"],

            "name": p["name"],

            "played": 0,

            "wins": 0,

            "losses": 0,

            "points": 0,

            "sets_for": 0,

            "sets_against": 0,

            "pts_for": 0,

            "pts_against": 0,

        }



    h2h: Dict[Tuple[int, int], int] = {}



    for m in matches:

        a = m["p1_id"]

        b = m["p2_id"]



        if a not in stats or b not in stats:

            continue



        a_sets = m["p1_sets"]

        b_sets = m["p2_sets"]

        a_pts = m["p1_points"]

        b_pts = m["p2_points"]



        stats[a]["played"] += 1

        stats[b]["played"] += 1



        stats[a]["sets_for"] += a_sets

        stats[a]["sets_against"] += b_sets

        stats[b]["sets_for"] += b_sets

        stats[b]["sets_against"] += a_sets



        stats[a]["pts_for"] += a_pts

        stats[a]["pts_against"] += b_pts

        stats[b]["pts_for"] += b_pts

        stats[b]["pts_against"] += a_pts



        if a_sets > b_sets:

            stats[a]["wins"] += 1

            stats[b]["losses"] += 1

            stats[a]["points"] += 2

            h2h[(a, b)] = 1

            h2h[(b, a)] = -1

        else:

            stats[b]["wins"] += 1

            stats[a]["losses"] += 1

            stats[b]["points"] += 2

            h2h[(a, b)] = -1

            h2h[(b, a)] = 1



    rows = []

    for s in stats.values():

        s["sets_diff"] = s["sets_for"] - s["sets_against"]

        s["pts_diff"] = s["pts_for"] - s["pts_against"]

        rows.append(s)



    def key_base(r: Dict):

        return (r["points"], r["wins"], r["sets_diff"], r["pts_diff"], r["pts_for"])



    rows.sort(key=key_base, reverse=True)



    i = 0

    while i < len(rows) - 1:

        j = i

        while j + 1 < len(rows) and key_base(rows[j]) == key_base(rows[j + 1]):

            j += 1



        if j > i:

            group = rows[i:j+1]

            if len(group) == 2:

                a_id = group[0]["id"]

                b_id = group[1]["id"]

                res = h2h.get((a_id, b_id))

                if res == -1:

                    rows[i], rows[i+1] = rows[i+1], rows[i]

        i = j + 1



    for idx, r in enumerate(rows, start=1):

        r["rank"] = idx

    return rows





def generate_schedule_fair(player_ids: List[int], days: int = 20, max_matches_per_day: int = 5):

    ids = sorted(player_ids)

    all_matches = {(a, b) for a, b in combinations(ids, 2)}

    scheduled = {d: [] for d in range(1, days + 1)}

    last_played = {p: 0 for p in ids}



    def idle(p, day):

        return day - last_played[p]



    for day in range(1, days + 1):

        used_today = set()



        remaining = len(all_matches)

        remaining_days = (days - day + 1)

        target = max(1, round(remaining / remaining_days))

        target = min(target, max_matches_per_day)



        while len(scheduled[day]) < target and all_matches:

            candidates = []

            for a, b in all_matches:

                if a in used_today or b in used_today:

                    continue

                score = idle(a, day) + idle(b, day)

                if last_played[a] == 0:

                    score += 1

                if last_played[b] == 0:

                    score += 1

                candidates.append((score, a, b))



            if not candidates:

                break



            candidates.sort(reverse=True, key=lambda x: x[0])

            _, a, b = candidates[0]



            scheduled[day].append((a, b))

            used_today.add(a)

            used_today.add(b)

            last_played[a] = day

            last_played[b] = day

            all_matches.remove((a, b))



    leftovers = list(all_matches)

    day = 1

    guard = 0

    while leftovers and guard < 100000:

        guard += 1

        used_today = {p for match in scheduled[day] for p in match}

        if len(scheduled[day]) < max_matches_per_day:

            a, b = leftovers[0]

            if a not in used_today and b not in used_today:

                scheduled[day].append((a, b))

                leftovers.pop(0)

            else:

                leftovers.append(leftovers.pop(0))

        day = day + 1 if day < days else 1



    return scheduled





def _detail_to_fields(detail: str):

    fields = {"s1a": "", "s1b": "", "s2a": "", "s2b": "", "s3a": "", "s3b": ""}

    if not detail:

        return fields

    parts = [p.strip() for p in detail.split(",") if p.strip()]

    for i, part in enumerate(parts[:3], start=1):

        if "-" not in part:

            continue

        a, b = part.split("-", 1)

        fields[f"s{i}a"] = a.strip()

        fields[f"s{i}b"] = b.strip()

    return fields





@app.get("/", response_class=HTMLResponse)

def home(request: Request, lang: str = "pl"):

    lang = (lang or "pl").lower()

    if lang not in ("pl", "de"):

        lang = "pl"



    conn = db()

    players = get_players(conn)

    matches = get_matches(conn)

    table = compute_table(players, matches)



    played_map = {}

    for m in matches:

        a = min(m["p1_id"], m["p2_id"])

        b = max(m["p1_id"], m["p2_id"])

        played_map[(a, b)] = m



    schedule_rows = get_schedule(conn)



    schedule_days = []

    current_day = None

    current_list = []



    for r in schedule_rows:

        if current_day is None:

            current_day = r["day_no"]



        if r["day_no"] != current_day:

            schedule_days.append((current_day, current_list))

            current_day = r["day_no"]

            current_list = []



        a = r["p1_id"]

        b = r["p2_id"]

        m = played_map.get((min(a, b), max(a, b)))



        item = {

            "day_no": r["day_no"],

            "p1_id": a,

            "p2_id": b,

            "p1_name": r["p1_name"],

            "p2_name": r["p2_name"],

            "played": bool(m),

            "p1_sets": m["p1_sets"] if m else "",

            "p2_sets": m["p2_sets"] if m else "",

            "p1_points": m["p1_points"] if m else "",

            "p2_points": m["p2_points"] if m else "",

            "sets_detail": m["sets_detail"] if m else "",

        }

        item.update(_detail_to_fields(item["sets_detail"]))

        current_list.append(item)



    if current_day is not None:

        schedule_days.append((current_day, current_list))



    conn.close()



    return templates.TemplateResponse(

    request=request,

    name="index.html",

    context={

        "request": request,

        "players": players,

        "matches": matches,

        "table": table,

        "lang": lang,

        "schedule_days": schedule_days,

    },

)

@app.get("/schedule/download")

def download_schedule(lang: str = "pl"):

    if lang not in ("pl", "de"):

        lang = "pl"



    conn = db()



    players = get_players(conn)

    schedule_rows = get_schedule(conn)

    matches = get_matches(conn)



    conn.close()



    # Wyniki rozegranych spotkań

    played_map = {}



    for match in matches:

        key = tuple(sorted((match["p1_id"], match["p2_id"])))

        played_map[key] = match



    lines = []



    # ==========================================

    # POLSKA WERSJA

    # ==========================================



    if lang == "pl":



        lines.extend([

            "TURNIEJ TENISA STOŁOWEGO",

            "=" * 50,

            "",

            "ZASADY",

            "-" * 50,

            "",

            "System rozgrywek: każdy z każdym",

            "Mecz: do 2 wygranych setów (best of 3)",

            "",

            "Punktacja tabeli:",

            "- zwycięstwo: 2 pkt",

            "- porażka: 0 pkt",

            "",

            "Przy równej liczbie punktów uwzględniane są",

            "kolejno zwycięstwa, bilans setów oraz małych punktów.",

            "",

            "",

            "ZAWODNICY",

            "-" * 50,

        ])



        for i, player in enumerate(players, start=1):

            lines.append(f"{i}. {player['name']}")



        lines.extend([

            "",

            "",

            "TERMINARZ",

            "=" * 50,

        ])



        filename = "terminarz_turnieju.txt"



    # ==========================================

    # NIEMIECKA WERSJA

    # ==========================================



    else:



        lines.extend([

            "TISCHTENNISTURNIER",

            "=" * 50,

            "",

            "REGELN",

            "-" * 50,

            "",

            "Spielsystem: Jeder gegen jeden",

            "Spiel: 2 Gewinnsätze (Best of 3)",

            "",

            "Punktewertung:",

            "- Sieg: 2 Punkte",

            "- Niederlage: 0 Punkte",

            "",

            "Bei Punktgleichheit werden Siege, Satzverhältnis",

            "und anschließend die kleinen Punkte berücksichtigt.",

            "",

            "",

            "TEILNEHMER",

            "-" * 50,

        ])



        for i, player in enumerate(players, start=1):

            lines.append(f"{i}. {player['name']}")



        lines.extend([

            "",

            "",

            "SPIELPLAN",

            "=" * 50,

        ])



        filename = "spielplan_turnier.txt"



    # ==========================================

    # TERMINARZ

    # ==========================================



    current_day = None

    match_number = 0



    for row in schedule_rows:



        if row["day_no"] != current_day:



            current_day = row["day_no"]

            match_number = 0



            lines.append("")

            lines.append("")



            if lang == "pl":

                lines.append(f"DZIEŃ {current_day}")

            else:

                lines.append(f"SPIELTAG {current_day}")



            lines.append("-" * 50)



        match_number += 1



        p1 = row["p1_name"]

        p2 = row["p2_name"]



        key = tuple(sorted((row["p1_id"], row["p2_id"])))



        played = played_map.get(key)



        if played:



            # Wynik setów

            if played["p1_id"] == row["p1_id"]:

                sets1 = played["p1_sets"]

                sets2 = played["p2_sets"]

            else:

                sets1 = played["p2_sets"]

                sets2 = played["p1_sets"]



            if lang == "pl":

                lines.append(

                    f"{match_number}. {p1} - {p2}    Wynik: {sets1}:{sets2}"

                )

            else:

                lines.append(

                    f"{match_number}. {p1} - {p2}    Ergebnis: {sets1}:{sets2}"

                )



            # Szczegóły setów

            if played["sets_detail"]:

                if lang == "pl":

                    lines.append(f"   Sety: {played['sets_detail']}")

                else:

                    lines.append(f"   Sätze: {played['sets_detail']}")



        else:



            if lang == "pl":

                lines.append(

                    f"{match_number}. {p1} - {p2}    Wynik: ___ : ___"

                )

            else:

                lines.append(

                    f"{match_number}. {p1} - {p2}    Ergebnis: ___ : ___"

                )



    if not schedule_rows:



        lines.append("")



        if lang == "pl":

            lines.append("Brak wygenerowanego terminarza.")

        else:

            lines.append("Kein Spielplan vorhanden.")



    # ==========================================

    # PODSUMOWANIE

    # ==========================================



    lines.extend([

        "",

        "",

        "=" * 50,

    ])



    total_matches = len(schedule_rows)

    played_matches = len(matches)



    if lang == "pl":



        lines.extend([

            "PODSUMOWANIE",

            "",

            f"Liczba zawodników: {len(players)}",

            f"Liczba zaplanowanych spotkań: {total_matches}",

            f"Rozegrane spotkania: {played_matches}",

            f"Pozostałe spotkania: {total_matches - played_matches}",

            "",

            "Powodzenia!",

        ])



    else:



        lines.extend([

            "ZUSAMMENFASSUNG",

            "",

            f"Teilnehmer: {len(players)}",

            f"Geplante Spiele: {total_matches}",

            f"Gespielte Spiele: {played_matches}",

            f"Verbleibende Spiele: {total_matches - played_matches}",

            "",

            "Viel Erfolg!",

        ])



    content = "\n".join(lines)



    return Response(

        content=content,

        media_type="text/plain; charset=utf-8",

        headers={

            "Content-Disposition": f'attachment; filename="{filename}"'

        },

    )



@app.post("/schedule/generate")

def schedule_generate(

    days: int = Form(20),

    admin_password: str = Form(""),

    lang: str = Form("pl"),

):

    require_admin(admin_password)



    if days < 1:

        days = 20

    if days > 60:

        days = 60



    if lang not in ("pl", "de"):

        lang = "pl"



    conn = db()

    players = get_players(conn)

    ids = [p["id"] for p in players]



    conn.execute("DELETE FROM schedule")



    if len(ids) >= 2:

        max_matches_per_day = len(ids) // 2

        sched = generate_schedule_fair(ids, days=days, max_matches_per_day=max_matches_per_day)



        for day_no in range(1, days + 1):

            for order, (a, b) in enumerate(sched.get(day_no, []), start=1):

                p1, p2 = (a, b) if a < b else (b, a)

                conn.execute("""

                    INSERT INTO schedule(day_no, order_in_day, p1_id, p2_id)

                    VALUES (%s, %s, %s, %s)

                """, (day_no, order, p1, p2))



    conn.commit()

    conn.close()

    return RedirectResponse(f"/?lang={lang}", status_code=303)





@app.post("/players/add")

def add_player(

    name: str = Form(...),

    admin_password: str = Form(""),

    lang: str = Form("pl"),

):

    require_admin(admin_password)



    if lang not in ("pl", "de"):

        lang = "pl"



    name = name.strip()

    if not name:

        return RedirectResponse(f"/?lang={lang}", status_code=303)



    conn = db()

    try:

        conn.execute("INSERT INTO players(name) VALUES (%s)", (name,))

        conn.commit()

    except psycopg.IntegrityError:

        pass

    finally:

        conn.close()



    return RedirectResponse(f"/?lang={lang}", status_code=303)





@app.post("/matches/add")

def add_match(

    p1_id: int = Form(...),

    p2_id: int = Form(...),

    s1a: Optional[int] = Form(None),

    s1b: Optional[int] = Form(None),

    s2a: Optional[int] = Form(None),

    s2b: Optional[int] = Form(None),

    s3a: Optional[str] = Form(None),

    s3b: Optional[str] = Form(None),

    admin_password: str = Form(""),

    lang: str = Form("pl"),

):

    require_admin(admin_password)



    def to_int_or_none(x):

        return int(x) if x not in (None, "") else None



    s1a = to_int_or_none(s1a)

    s1b = to_int_or_none(s1b)

    s2a = to_int_or_none(s2a)

    s2b = to_int_or_none(s2b)

    s3a = to_int_or_none(s3a)

    s3b = to_int_or_none(s3b)



    if lang not in ("pl", "de"):

        lang = "pl"



    if p1_id == p2_id:

        return RedirectResponse(f"/?lang={lang}", status_code=303)



    payload = parse_sets_best_of_3(s1a, s1b, s2a, s2b, s3a, s3b)

    if payload is None:

        return RedirectResponse(f"/?lang={lang}", status_code=303)



    a, b, normalized = normalize_pair(p1_id, p2_id, payload)



    conn = db()

    conn.execute("""

        INSERT INTO matches(p1_id, p2_id, p1_sets, p2_sets, p1_points, p2_points, sets_detail)

        VALUES (%s, %s, %s, %s, %s, %s, %s)

        ON CONFLICT(p1_id, p2_id)

        DO UPDATE SET

            p1_sets=excluded.p1_sets,

            p2_sets=excluded.p2_sets,

            p1_points=excluded.p1_points,

            p2_points=excluded.p2_points,

            sets_detail=excluded.sets_detail,

            played_at=CURRENT_TIMESTAMP

    """, (

        a, b,

        normalized["p1_sets"], normalized["p2_sets"],

        normalized["p1_points"], normalized["p2_points"],

        normalized["sets_detail"]

    ))

    conn.commit()

    conn.close()



    return RedirectResponse(f"/?lang={lang}", status_code=303)





@app.post("/matches/delete")

def delete_match(

    match_id: int = Form(...),

    admin_password: str = Form(""),

    lang: str = Form("pl"),

):

    require_admin(admin_password)



    if lang not in ("pl", "de"):

        lang = "pl"



    conn = db()

    conn.execute("DELETE FROM matches WHERE id=%s", (match_id,))

    conn.commit()

    conn.close()

    return RedirectResponse(f"/?lang={lang}", status_code=303)





@app.post("/reset")

def reset_all(

    admin_password: str = Form(""),

    lang: str = Form("pl"),

):

    require_admin(admin_password)



    if lang not in ("pl", "de"):

        lang = "pl"



    conn = db()

    conn.execute("DELETE FROM matches")

    conn.execute("DELETE FROM players")

    conn.execute("DELETE FROM schedule")

    conn.commit()

    conn.close()

    return RedirectResponse(f"/?lang={lang}", status_code=303) 